apiVersion: batch/v1
kind: Job
metadata:
  name: "migration-v1-job"
  labels:
    app: migration-v1-job
spec:
  backoffLimit: 10
  template:
    metadata:
      name: "migration-v1-job"
    spec:
      restartPolicy: Never
      containers:
        - name: migration-v1-job
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              PGCONNECT_TIMEOUT=5 psql postgresql://hw2-user:hw2-pwd@postgresql:5433/hw2-db -c 'CREATE TABLE IF NOT EXISTS users (id UUID primary key, username varchar(255) UNIQUE NOT NULL, first_name varchar NOT NULL, last_name varchar NOT NULL, email varchar NOT NULL, phone varchar NOT NULL)'
